-- DELETE  from T_PARTITIONING where TYPE = 'PERSON';
SELECT * from T_PARTITIONING;


INSERT INTO T_PARTITIONING(TYPE, MIN_VALUE, MAX_VALUE, TOTAL_VALUE)
WITH CTE AS (SELECT /*+  parallel(T,120) */  SEQ_NUMBER, NTILE(30) OVER (ORDER BY SEQ_NUMBER) AS ID FROM T_PERSON_V2 T WHERE SENT_TO_LI BETWEEN 0 AND 2) 
SELECT 'PERSON', MIN(SEQ_NUMBER) AS MIN_VALUE, MAX(SEQ_NUMBER) AS MAX_VALUE, COUNT(*) AS TOTAL_VALUE FROM CTE GROUP BY ID ORDER BY ID;




INSERT INTO T_PARTITIONING(TYPE, MIN_VALUE, MAX_VALUE, TOTAL_VALUE)
WITH CTE AS (SELECT /*+  parallel(T,120) */ SEQ_NUMBER, NTILE(10) OVER (ORDER BY SEQ_NUMBER) AS ID FROM T_COMPANY_V2 T WHERE SENT_TO_CMP BETWEEN 0 AND 2)
SELECT 'COMPANY', MIN(SEQ_NUMBER) AS MIN_VALUE, MAX(SEQ_NUMBER) AS MAX_VALUE, COUNT(*) AS TOTAL_VALUE FROM CTE GROUP BY ID ORDER BY ID;